### ISSUE TITLE
Propose one theme for JBoss Outreach blog website

### ISSUE THREAD

**Issue by garg-anuj** [jboss-outreach/blog.jboss-outreach.org#3]

**Comment by Vishwas-Adiga** [comment]
Hi
Here is the link to my theme proposal:
https://docs.google.com/document/d/12tKBMBSLvHv17PxeYvNgdNnAr3UVmEISgX4VhgUhy0A/edit?usp=sharing

**Comment by SachinRammoorthy** [comment]
Hey. Here is the link to my proposal.
https://docs.google.com/document/d/1Gu2mCYl3cUel4mtt3IJ0outmTM1ny0nX3-1dI4z8Xno/edit

Thanks. Let me know if there are any modifications to be made.

**Comment by navanavi3** [comment]
My theme proposal : https://docs.google.com/document/d/1e6Z8jH5sZqmduLD052hfTIpk5FgnufkuRR3e1FWBeZk/edit?usp=sharing

**Comment by sidhyatikku** [comment]
Hi ! Here's my link

https://drive.google.com/open?id=1Jn25SV8IDFGWso7JNImfoueqDzEEMeEiEdLoc1hZwXQ

**For any issues please reach me on JBoss irc**
