### ISSUE TITLE
Individual blog contents: background color issue 

### ISSUE THREAD

**Issue by divyanshkul** [jboss-outreach/blog.jboss-outreach.org#85]
The background color of the individual blog content is somewhat isn't correct, it is black background all over, thus the text is not clearly visible.

It's probably because of a bad merge. Will try to fix it. 

Screenshot: 
![image](https://user-images.githubusercontent.com/34028379/34838454-2da6e87a-f724-11e7-926a-e715257a04a3.png)

**Comment by vicens-aniol** [comment]
@divyanshkul I think u should change text colour to white ;D

**Comment by vicens-aniol** [comment]
@divyanshkul I think the issue is in the footer

**Comment by divyanshkul** [comment]
Hey @vicens-aniol It is indeed in the footer, I'll be making my PR in sometime, I think I have found the issue, just reading some docs about the issue. Btw if you fix it anytime soon, do tell me. :D

**Comment by divyanshkul** [comment]
https://github.com/jboss-outreach/blog.jboss-outreach.org/pull/86 fixes this. 
Closed.
